name: MYCI
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    container:
      image: node:8
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
    steps:
    - uses: actions/checkout@v1
    - run: |
        node -v
        curl localhost:8080
